name: CI for ESP32 Blink LED con PlatformIO

on:
  push:
    branches:
      - develop
  #pull_request:
  #  branches:
  #    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [esp32dev, unit]  # List your environments here


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python3 -m pip install --upgrade platformio


    - name: Testing with PlatformIO
      if: matrix.environment == 'unit'
      run: |
          platformio test --environment unit 
    
    
    - name: Compile with PlatformIO
      if: matrix.environment == 'esp32dev'
      run: |
          platformio run --environment esp32dev 
      #run: |
      #  platformio run

#    - name: Upload firmware artifact
#      if: always()
#      uses: actions/upload-artifact@v3
#      with:
#        name: blinkled-firmware
#        path: ./.pio/build/esp32dev/firmware.bin

