name: Integracion Continua

on:
  push:
    branches:
  #   - develop
      - main
  #pull_request:
  # branches:
  #  - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo message
      run: |
        echo "Bienvenidos Ingenieros"
