name: Integracion Continua

on:
  push:
    branches:
      - develop
  #pull_request:
  # branches:
  #  - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Echo message
      run: |
        echo "Hola Ingenieros"
